Repository twitterjs/twitter.js, pull requests merged in 2021-11, with the labels that each got.

#67 feat: add support for manage tweet endpoints
  package-lock.json
  package.json
  src/managers/TweetManager.ts
  src/structures/Tweet.ts
  src/structures/TweetPayload.ts
  src/structures/index.ts
  src/typings/Interfaces.ts
  src/typings/Types.ts
Labels: api support

#68 types: fetching rules returns a collection when option is undefined
  src/typings/Types.ts
Labels: typings

#70 adding contribution guide
  CONTRIBUTING.md
Labels: documentation, chore
