Repository twitterjs/twitter.js, pull requests merged in 2022-02, with the labels that each got.

#153 feat: add list methods
  src/structures/SimplifiedList.ts
  src/structures/SimplifiedTweet.ts
  src/structures/Tweet.ts
Labels: enhancement

#154 feat: add support for sort_order parameter
  package-lock.json
  package.json
  src/books/SearchTweetsBook.ts
  src/typings/Interfaces.ts
Labels: api support

#155 refactor: replace `Snowflake` with `string`
  package-lock.json
  package.json
  src/books/BaseRangeBook.ts
  src/books/BlockedUsersBook.ts
  src/books/ComposedTweetsBook.ts
  src/books/FollowedListsBook.ts
  src/books/LikedByUsersBook.ts
  src/books/LikedTweetsBook.ts
  src/books/ListFollowersBook.ts
  src/books/ListMembersBook.ts
  src/books/ListTweetsBook.ts
  src/books/MemberOfListsBook.ts
  src/books/MutedUsersBook.ts
  src/books/OwnedListsBook.ts
  src/books/PinnedListsBook.ts
  src/books/RetweetedByUsersBook.ts
  src/books/SearchTweetsBook.ts
  src/books/SpaceTicketBuyersBook.ts
  src/books/UserFollowersBook.ts
  src/books/UserFollowingsBook.ts
  src/books/UserMentioningTweetsBook.ts
  src/client/Client.ts
  src/index.ts
  src/managers/FilteredStreamRuleManager.ts
  src/managers/ListManager.ts
  src/managers/SpaceManager.ts
  src/managers/TweetManager.ts
  src/managers/UserManager.ts
  src/managers/__tests__/BaseManager.test.ts
  src/structures/BaseStructure.ts
  src/structures/SimplifiedList.ts
  src/structures/SimplifiedSpace.ts
  src/structures/SimplifiedTweet.ts
  src/structures/SimplifiedUser.ts
  src/structures/misc/Miscellaneous.ts
  src/structures/misc/TweetEntities.ts
  src/typings/Interfaces.ts
  src/typings/Types.ts
Labels: refactor, typings, dependencies

#156 feat: add support for subscriber_count and GET /2/spaces/:id/tweets endpoint
  .husky/commit-msg
  .husky/pre-commit
  package-lock.json
  package.json
  src/managers/SpaceManager.ts
  src/structures/SimplifiedSpace.ts
  src/util/Constants.ts
Labels: api support, dependencies

#157 refactor: make required parameters positional
  README.md
  package.json
  src/books/BaseBook.ts
  src/books/BaseRangeBook.ts
  src/books/BlockedUsersBook.ts
  src/books/ComposedTweetsBook.ts
  src/books/FollowedListsBook.ts
  src/books/LikedByUsersBook.ts
  src/books/LikedTweetsBook.ts
  src/books/ListFollowersBook.ts
  src/books/ListMembersBook.ts
  src/books/ListTweetsBook.ts
  src/books/MemberOfListsBook.ts
  src/books/MutedUsersBook.ts
  src/books/OwnedListsBook.ts
  src/books/PinnedListsBook.ts
  src/books/RetweetedByUsersBook.ts
  src/books/SearchTweetsBook.ts
  src/books/SpaceTicketBuyersBook.ts
  src/books/TweetsCountBook.ts
  src/books/UserFollowersBook.ts
  src/books/UserFollowingsBook.ts
  src/books/UserMentioningTweetsBook.ts
  src/client/BaseClient.ts
  src/client/Client.ts
  src/errors/TwitterjsError.ts
  src/index.ts
  src/managers/BaseManager.ts
  src/managers/FilteredStreamRuleManager.ts
  src/managers/ListManager.ts
  src/managers/SpaceManager.ts
  src/managers/TweetManager.ts
  src/managers/UserManager.ts
  src/rest/APIRequest.ts
  src/rest/RESTManager.ts
  src/structures/BaseStructure.ts
  src/structures/SimplifiedList.ts
  src/structures/SimplifiedTweet.ts
  src/structures/TweetPayload.ts
  src/structures/misc/Miscellaneous.ts
  src/typings/Interfaces.ts
  src/typings/Types.ts
  src/typings/index.ts
  src/util/Constants.ts
  src/util/Utility.ts
  tsconfig.declaration.json
  tsconfig.json
Labels: refactor, chore
